### PR TITLE
backport to Summernote 0.6.16

### PR DESCRIPTION
**Pull request by zeroheure**
Nothing to say, just adapted your code. Not very clean though, because I'm not a dev.

### CODE REVIEW

**Comment by tylerecouture** [comment]
Cool! I'm not really a dev either =) So I don't even know what to do with this.  I assume I want to merge this with a 0.6.16 branch?  I don't wanna overwrite the base with a backport....

**Comment by tylerecouture** [comment]
I created a backport branch.  Can you change the PR to that one? Thanks!

**Comment by zeroheure** [comment]
I will do it this afternoon, many thanks !

**Comment by zeroheure** [comment]
Actually, I've done this backport to use your plugin with [Odoo](https://github.com/odoo) (an ERP). Odoo web editor is still based on this old Summernote version. I'm working on porting various modules to improve the web editor regarding programmers need, SEO, etc. 
Modules will be on zeroheure/odoo-seo (or similar). I plan to sell some of them while keeping source code available for free.

**Pull request merged**
